/**
 * Created by youyu on 2018/8/20.
 */
export const RECORD_USERINFO = 'RECORD_USERINFO';
export const SET_USERINFO = 'SET_USERINFO';
export const UPDATE_USERINFO = 'UPDATE_USERINFO';
export const RECORD_COLLECT = 'RECORD_COLLECT';
export const CANCEL_COLLECT = 'CANCEL_COLLECT';
export const CLEAN_INVALID_COLLECT_PRODUCT = 'CLEAN_INVALID_COLLECT_PRODUCT';
export const INIT_CART = 'INIT_CART';
export const ADD_CART = 'ADD_CART';
export const DELETE_CART = 'DELETE_CART';
export const ADD_SELECT_PRODUCT = 'ADD_SELECT_PRODUCT';
export const DELECT_SELECT_PRODUCT = 'DELECT_SELECT_PRODUCT';
export const ADD_OR_MINUS = 'ADD_OR_MINUS';
export const CLEAR_INVALID_PRODUCT = 'CLEAR_INVALID_PRODUCT';
export const SET_AREA_LIST = 'SET_AREA_LIST';
export const SET_ADDRESS = 'SET_ADDRESS';
export const UPDATE_ADDRESS = 'UPDATE_ADDRESS';
export const SET_CONFIRM_ADDRESS = 'SET_CONFIRM_ADDRESS';
export const SET_REDEEM = 'SET_REDEEM';
